# Generated by Django 4.0.3 on 2022-03-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
