# Generated by Django 4.0.3 on 2022-03-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='features',
            field=models.TextField(default='', max_length=100),
        ),
    ]
