# Generated by Django 4.0.3 on 2022-05-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_apartment_features_alter_property_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='property_id',
            new_name='property',
        ),
    ]
