# Generated by Django 4.0.3 on 2022-03-18 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.IntegerField()),
                ('emergency_contact', models.IntegerField()),
                ('id_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('date_of_entry', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
